#!/bin/sh

echo "rotate_counter_clockwise();translate(0,1);"
echo "flip_vertical();translate(-4,3);"
echo ""
echo "flip_vertical();translate(-5,-1);"
echo "flip_horizontal();translate(-1,1);"
echo "translate(1,-3);rotate_clockwise();rotate_clockwise();rotate_clockwise();rotate_clockwise();"
echo "translate(-3,-4);"
